"""Mako template for revision files"""

"""Add Stripe fields to User model

Revision ID: 6c6b303caa39
Revises: dcc1b80f1ed7
Create Date: 2025-12-18 09:30:41.720050

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c6b303caa39"
down_revision = "dcc1b80f1ed7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_users_stripe_customer_id"), "users", ["stripe_customer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_stripe_customer_id"), table_name="users")
    op.drop_column("users", "stripe_subscription_id")
    op.drop_column("users", "stripe_customer_id")
    # ### end Alembic commands ###
