"""Mako template for revision files"""

"""Add ChatSession, DailyPulse and other missing tables

Revision ID: dcc1b80f1ed7
Revises: f0e97ec97158
Create Date: 2025-12-18 09:19:26.333509

"""


# revision identifiers, used by Alembic.
revision = "dcc1b80f1ed7"
down_revision = "f0e97ec97158"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
